import {ScanOption } from "@/lib/types/settings";

export const SCAN_SETTINGS: ScanOption = {
  // File System
  recursive: {
    label: "Recursive",
    flag: "--recursive",
    group: "filesystem",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: true },
  },
  crossFs: {
    label: "Scan other mounted filesystems",
    flag: "--cross-fs",
    group: "filesystem",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },
  followDirSymlinks: {
    label: "Follow directory symlinks",
    flag: "--follow-dir-symlinks",
    group: "filesystem",
    conflictsWith: [],
    dependsOn: [],
    value: {
	 kind: "choice",
	 default: 1,
	 choices: [
	   { label: "Never", value: 0 },
	   { label: "Only if passed explicitly", value: 1 },
	   { label: "Always", value: 2 },
	 ],
    },
  },
  followFileSymlinks: {
    label: "Follow file symlinks",
    flag: "--follow-file-symlinks",
    group: "filesystem",
    conflictsWith: [],
    dependsOn: [],
    value: {
	 kind: "choice",
	 default: 1,
	 choices: [
	   { label: "Never", value: 0 },
	   { label: "Only if passed explicitly", value: 1 },
	   { label: "Always", value: 2 },
	 ],
    },
  },

  // Output
  quiet: {
    label: "Suppress normal output",
    flag: "--quiet",
    group: "output",
    conflictsWith: ["verbose", "infected"],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },
  verbose: {
    label: "Output detailed logs",
    flag: "--verbose",
    group: "output",
    conflictsWith: ["quiet", "infected"],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },
  infected: {
    label: "List only infected files",
    flag: "--infected",
    group: "output",
    conflictsWith: ["verbose", "quiet"],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },
  noSummary: {
    label: "Hide scan summary",
    flag: "--no-summary",
    group: "output",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },
  bell: {
    label: "Play sound on detection",
    flag: "--bell",
    group: "output",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },
  debug: {
    label: "Debug output",
    description: "Display debug messages from libclamav.",
    flag: "--debug",
    group: "advanced",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },

  // Detection
  algorithmicDetection: {
    label: "Algorithmic detection",
    flag: "--algorithmic-detection",
    group: "detection",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: true },
  },
  heuristicAlerts: {
    label: "Heuristic alerts",
    description: "May increase false positives.",
    flag: "--heuristic-alerts",
    group: "advanced",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: true },
  },
  heuristicPrecedence: {
    label: "Heuristic scan precedence",
    flag: "--heuristic-scan-precedence",
    group: "advanced",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },
  detectPUA: {
    label: "Detect Possibly Unwanted Applications (PUA)",
    flag: "--detect-pua",
    group: "detection",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },
  detectStructured: {
    label: "Detect SSN and credit card numbers",
    flag: "--detect-structured",
    group: "detection",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },
  structuredSSNFormat: {
    label: "SSN format",
    flag: "--structured-ssn-format",
    group: "advanced",
    conflictsWith: [],
    dependsOn: ["detectStructured"],
    value: {
	 kind: "choice",
	 default: 0,
	 choices: [
	   { label: "xxx-yy-zzzz", value: 0 },
	   { label: "xxxyyzzzz", value: 1 },
	   { label: "Both formats", value: 2 },
	 ],
    },
  },
  structuredSSNCount: {
    label: "SSN detection threshold",
    flag: "--structured-ssn-count",
    group: "advanced",
    conflictsWith: [],
    dependsOn: ["detectStructured"],
    value: { kind: "input", inputType: "number", min: 1, max: 100 },
  },
  structuredCCCount: {
    label: "Credit card detection threshold",
    flag: "--structured-cc-count",
    group: "advanced",
    conflictsWith: [],
    dependsOn: ["detectStructured"],
    value: { kind: "input", inputType: "number", min: 1, max: 100 },
  },

  // File Types
  scanPE: {
    label: "Scan PE files",
    flag: "--scan-pe",
    group: "file-types",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: true },
  },
  scanELF: {
    label: "Scan ELF files",
    flag: "--scan-elf",
    group: "file-types",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: true },
  },
  scanOLE2: {
    label: "Scan Office / MSI files",
    flag: "--scan-ole2",
    group: "file-types",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: true },
  },
  scanPDF: {
    label: "Scan PDF files",
    flag: "--scan-pdf",
    group: "file-types",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: true },
  },
  scanHTML: {
    label: "Scan HTML files",
    flag: "--scan-html",
    group: "file-types",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: true },
  },
  scanArchive: {
    label: "Scan archives",
    flag: "--scan-archive",
    group: "file-types",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: true },
  },
  scanMail: {
    label: "Scan mail files",
    flag: "--scan-mail",
    group: "file-types",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: true },
  },
  detectBroken: {
    label: "Detect broken executables",
    flag: "--detect-broken",
    group: "advanced",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },

  // Limits / Performance
  maxFileSize: {
    label: "Max file size (KB)",
    flag: "--max-filesize",
    group: "limits-performance",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "input", inputType: "number", min: 64, max: 1024 * 1024, default: 100_000 },
  },
  maxScanSize: {
    label: "Max scan size (KB)",
    flag: "--max-scansize",
    group: "limits-performance",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "input", inputType: "number", min: 64, max: 1024 * 1024, default: 400_000 },
  },
  alertEncrypted: {
    label: "Alert on encrypted archives or documents",
    flag: "--alert-encrypted",
    group: "output",
    conflictsWith: [],
    dependsOn: [],
    value: {kind: "yes-no", default: true}
  },
  maxFiles: {
    label: "Max extracted files",
    flag: "--max-files",
    group: "limits-performance",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "input", inputType: "number", min: 1, max: 100000 },
  },
  maxRecursion: {
    label: "Archive recursion limit",
    flag: "--max-recursion",
    group: "limits-performance",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "input", inputType: "number", min: 1, max: 50 },
  },
  maxDirRecursion: {
    label: "Directory recursion depth",
    flag: "--max-dir-recursion",
    group: "limits-performance",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "input", inputType: "number", min: 1, max: 100 },
  },

  // Advanced
  noCerts: {
    label: "Disable Authenticode verification",
    flag: "--nocerts",
    group: "advanced",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },
  disableCache: {
    label: "Disable cache",
    flag: "--disable-cache",
    group: "advanced",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },
  officialDbOnly: {
    label: "Use only official databases",
    flag: "--official-db-only",
    group: "advanced",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },
  leaveTemps: {
    label: "Do not remove temporary files",
    flag: "--leave-temps",
    group: "advanced",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: false },
  },
  bytecode: {
    label: "Enable bytecode",
    flag: "--bytecode",
    group: "advanced",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "yes-no", default: true },
  },
  bytecodeUnsigned: {
    label: "Allow unsigned bytecode",
    description: "Dangerous. Use only for testing.",
    flag: "--bytecode-unsigned",
    group: "advanced",
    conflictsWith: [],
    dependsOn: ["bytecode"],
    value: { kind: "yes-no", default: false },
  },
  bytecodeTimeout: {
    label: "Bytecode timeout (ms)",
    flag: "--bytecode-timeout",
    group: "advanced",
    conflictsWith: [],
    dependsOn: ["bytecode"],
    value: { kind: "input", inputType: "number", min: 100, max: 60000 },
  },
  databasePath: {
    label: "Database path",
    flag: "--database",
    group: "advanced",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "input", inputType: "path" },
  },
  tempDir: {
    label: "Temporary files directory",
    flag: "--tempdir",
    group: "advanced",
    conflictsWith: [],
    dependsOn: [],
    value: { kind: "input", inputType: "path" },
  },
}

const array = Object.entries(SCAN_SETTINGS).map(([key,obj])=>({
  ...obj,
  optionKey: key
}))

export const SCAN_SETTINGS_GROUPED = Object.groupBy(array,({group})=>group)